<?php

class Person {
    public $name, $address, $age;
    public function birthday() {
        echo "This is a birdthday\n";
    }
}
class Employee extends Person {
    public $position, $salaru;
    public function birthday()
    {
        parent::birthday(); // TODO: Change the autogenerated stub
        echo "This is a birdthday from Employer\n";
    }
}
$obj = new Person();
$obj->birthday();
$obj = new Employee();
$obj->birthday();
?>

