<?php
<<<<<<< HEAD
class Person
{
    public $age;
    public function __construct() {
        $this->age = 0;
    }
    public function incrementAge() {
        $this->age += 1;
        $this->ageChanged();
    }
    protected function decrementAge() {
        $this->age -= 1;
        $this->ageChanged();;
    }
    private function ageChanged() {
        echo "Age changed to {$this->age}\n";
    }

    public $name = '';
    function getName() {
        return $this->name;
    }
    function setName ($newName) {
        $this->name = $newName;
    }
}

class SupernaturalPerson extends Person {
    public function inSupernatural() {
        $this->decrementAge();
    }
}

$person = new Person();
echo $person->age . "\n";
$person->incrementAge();
$person1 = new SupernaturalPerson();
echo $person1->inSupernatural();
$person1-> incrementAge();
?>


<?php
class HTMLStuff {
    static function startTable() {
        echo "<table border=\"1\">\n";
    }
    static function endTable() {
        echo "</table>\n";
    }
}
HTMLStuff::startTable();
HTMLStuff::endTable();
?>
=======

class Person {
    public $name, $address, $age;
    public function birthday() {
        echo "This is a birdthday\n";
    }
}
class Employee extends Person {
    public $position, $salaru;
    public function birthday()
    {
        parent::birthday(); // TODO: Change the autogenerated stub
        echo "This is a birdthday from Employer\n";
    }
}
$obj = new Person();
$obj->birthday();
$obj = new Employee();
$obj->birthday();
?>

>>>>>>> bbcf5b68b2329aa04988e24aba15dfec536774d5
