<?php
/*trait Command {
    function run() {
        echo "Executing a command\n";
    }
}
trait Marathon {
    function run() {
        echo "Running a marathon\n";
    }
}
class Person {
    use Command, Marathon {
        Command::run as runCommand;
        Marathon::run insteadof Command;
    }
}
$person = new Person();
$person->runCommand();
$person->run();
*/?>
<?php
/*abstract class Component {
    abstract function printOutput();
}

interface exampleInterface {
    public function default_function();
}
class ImageComponent extends Component {
    public function printOutput()
    {
        echo "Pretty picture\n";       // TODO: Implement printOutput() method.
    }
}

class InterExample implements exampleInterface {
    public function default_function()
    {
        echo "Default function\n";    // TODO: Implement default_function() method.
    }
}
$object = new ImageComponent();
$object->printOutput();

$object2 = new InterExample();
$object2->default_function();
*/?>

<?php
/*trait Sortable {
    abstract function uniqueId();
    function compareById($object) {
        return ($object->uniqueId() < $this->uniqueId()) ? -1 : 1;
    }
}

class Bird {
    use Sortable;
    function uniqueId()
    {
        return 2;    // TODO: Implement uniqueId() method.
    }
}

class Car {
    use Sortable;
    public function uniqueId()
    {
        return 10;   // TODO: Implement uniqueId() method.
    }
}

$bird = new Bird();
$car = new Car();
$comparison = $bird->compareById($car);
echo $comparison;
?>
<?php
/*class Person {
    public $name = '';
    function getName() {
        return $this->name;
    }
}
$anonymous = new class(){
    function getName()
    {
        return "Data warehousing"; // TODO: Change the autogenerated stub
    }
};

?>
echo $anonymous->getName();*/
?>
<?php
/*    class Person {

    }
    class Employee extends Person {

    }
    echo class_exists("Person") . "\n";
    $classes = get_declared_classes();
    var_dump($classes);
    echo in_array("Employee" , (array)$classes) . "\n";
*/?>

<?php
class Person {
    private $name = '';

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name): void {
        $this->name = $name;
    }
}

class Employee extends Person {
    private $salary = 0;
    public $yob = 0;
    public function getSalary(): int {
        return $this->salary;
    }
    public function setSalary(int $salary): void {
        $this->salary = $salary;
    }
}
var_dump(get_class_methods("Employee")); // od parametrow
var_dump(get_class_vars("Employee")); // od pol
?>